const productsData = {
  newProducts: [
    {
      id: 1,
      name: "Bộ Bài Uno 108 Lá",
      image: "../image/108UNO-825-bo-bai-uno-108-la-bang-giay-215x215.jpg",
      price: 15000,
    },
    {
      id: 2,
      name: "Đồ Chơi Bàn Cờ Tỷ Phú Lớn",
      image: "../image/1168-do-choi-ban-co-ty-phu-lon-bang-nhua-size-44-cm-215x215.jpg",
      price: 60000,
    },
    {
      id: 3,
      name: "Đồ Chơi Đàn Gỗ Xylophone",
      image: "../image/1196-do-choi-dan-go-xylophone-8-thanh-bang-sat-215x215.jpg",
      price: 40000,
    },
    {
      id: 4,
      name: "Đồ Chơi Bản Phi Tiêu Nam Châm",
      image: "../image/1630-do-choi-bang-phi-tieu-nam-cham-hit-25-cm-215x215.jpg",
      price: 40000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Đồ Chơi Láp Ráp Cây Thông",
      image: "../image/1622-do-choi-lap-rap-xe-hinh-cay-thong-noel-giang-sinh-215x215.jpg",
      price: 35000,
      promotion: "new",
    },
    {
      id: 6,
      name: "Mô Hình Xe Container Mini ",
      image: "../image/1633-mo-hinh-xe-container-cho-hang-mini-bang-nhua-chay-tron-215x215.jpg",
      price: 10000,
    },
    {
      id: 7,
      name: "Đồ Chơi Xe Tải Đầu Kéo 3 Tầng",
      image: "../image/1634-do-choi-xe-tai-dau-keo-3-tang-cho-6-xe-bang-nhua-chay-tron-215x215.jpg",
      price: 55000,
    },
    {
      id: 8,
      name: "Đồ Chơi Mô Hình Máy Bay",
      image: "../image/1635-do-choi-mo-hinh-may-bay-cho-khach-dieu-khien-tu-xa-2-kenh-tien-lui-215x215.jpg",
      price: 70000,
      promotion: "new",
    },
    {
      id: 9,
      name: "Hộp Đồ Chơi Vali Đồ Nghề",
      image: "../image/1636-hop-do-choi-va-li-do-nghe-sua-chua-cho-be-215x215.jpg",
      price: 270000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Bàn Cờ Cá Ngựa Lớn",
      image: "../image/ban-ca-ngua-lon-lien-hiep-thanh-215x215.jpg",
      price: 77000,
      decrease:60000,
    },
    {
      id: 11,
      name: "Đồ Chơi 8 Xe Robocar",
      image: "../image/do-choi-8-xe-robocar-poli-chay-tron-215x215.jpg",
      price: 110000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Đồ Chơi Xe Đẩy",
      image: "../image/do-choi-xe-day.jpg",
      price: 120000,
      decrease:100000,
    },
    {
      id: 13,
      name: "Bàn Trò Chơi Lắc Bầu Cua Cá Cọp",
      image: "../image/1285-ban-tro-choi-lac-bau-cua-ca-cop-xuc-xac-bang-xop-44-43-cm-215x215.jpg",
      price: 60000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Đồ Chơi Đồng Xu Bằng Nhựa",
      image:"../image/1283-do-choi-dong-xu-trung-bang-nhua-cho-be-215x215.jpg",
      price: 15000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Đồ Chơi Ném Vòng Bằng Nhựa",
      image: "../image/1637-do-choi-nem-vong-bang-nhua-1-vong-1-tru-215x215.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 16,
      name: "Đồ Chơi Mô Hình Xe Tăng Mini",
      image: "../image/1631-do-choi-mo-hinh-xe-tang-mini-bang-nhua-chay-tron-215x215.jpg",
      price: 6000,
      promotion: "new",
    },
    {
      id: 17,
      name: "Đồ Chơi Lò Xo Bóp Tay Càng Cua",
      image: "../image/1629-do-choi-lo-xo-bop-tay-bang-cua-bang-nhua-215x215.jpg",
      price: 40000,
      promotion: "new",
    },
    {
      id: 18,
      name: "Đồ Chơi Mô Hình Khủng Long Tê Giác 3 Sừng",
      image: "../image/1626-do-choi-mo-hinh-khung-long-te-giac-3-sung-nhoi-bong-co-nhac-215x215.jpg",
      price: 65000,
      promotion: "new",
    },
    {
      id: 19,
      name: "Đồ Chơi Mô Hình Cá Sấu",
      image: "../image/1624-do-choi-mo-hinh-ca-sau-nhoi-bong-bang-nhua-mem-215x215.jpg",
      price: 150000,
      promotion: "new",
    },
    {
      id: 20,
      name: "Đồ Chơi Ống Kính Vạn Hoa",
      image: "../image/1620-do-choi-ong-kinh-van-hoa-ma-thuat-ong-nhom-cho-be-215x215.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 21,
      name: "Mô Hình Quân Sự Lính Nhựa",
      image: "../image/JL668-968-mo-hinh-quan-su-linh-nhua-militara-action-225x225.jpg",
      price: 83000,
      decrease: 75000,
    },
    {
      id: 22,
      name: "Bộ Đồ Chơi Các Loại Côn Trùng",
      image: "../image/1621-bo-do-choi-ca-loai-con-trung-dai-thanh-loc-bang-nhua-215x215.jpg",
      price: 95000,
      promotion: "new",
    },
    {
      id: 23,
      name: "Bộ Đồ Chơi Lô Tô",
      image: "../image/MT90-408-bo-tro-choi-lo-to-90-so-bang-giay-va-go-215x215.jpg",
      price: 25000,
    },
    {
      id: 24,
      name: "Đồ Chơi Mô Hình Khủng Long Godzilla",
      image:
        "../image/1625-do-choi-mo-hinh-khung-long-godzilla-bang-cao-su-mem-215x215.jpg",
      price: 3500000,
      decrease: 2333000,
    },
  ],
  doChoiTreSoSinh: [
    {
      id: 1,
      name: "Đồ Chơi Búa Đập Mèo",
      image: "../image/1368-do-choi-bua-dap-mon-phat-ra-am-thanh-180x180.jpg",
      price: 15000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Bộ Đồ Chơi Lục Lạc Treo Nôi",
      image: "../image/1325-bo-do-choi-luc-lac-treo-noi-nhieu-mon-dynamic-baby-180x180.jpg",
      price: 70000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Đồ Chơi Lắc Tạ 2 Banh Cầm Tay",
      image: "../image/1312-do-choi-lac-ta-cam-tay-lac-2-banh-cho-be-bang-nhua-phat-ra-am-thanh-180x180.jpg",
      price: 8000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Đồ Chơi Trống Lắc Cầm Tay",
      image: "../image/1022-do-choi-trong-lac-cam-tay-hoa-tiet-dan-gian-bang-nhua-180x180.jpg",
      price: 15000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Đồ Chơi Heo Mẹ Và 3 Chú Heo Con",
      image: "../image/10020do-choi-heo-me-va-3-chu-heo-con-chit-tui-luoi-180x180.jpg",
      price: 24000,
      promotion: "new",
    },
    {
      id: 6,
      name: "Đồ Chơi Lò Xo Bóp Tay Đầu Sư Tử",
      image: "../image/428-682-do-choi-lo-xo-bop-tay-dau-su-tu-bang-nhua-180x180.jpg",
      price: 33000,
      promotion: "new",
    },
    {
      id: 7,
      name: "Đồ Chơi Lục Lạc Treo Nôi",
      image: "../image/997-959-do-choi-luc-lac-treo-noi-10-mon-baby-set-180x180.jpg",
      price: 106000,
      promotion: "new",
    },
    {
      id: 8,
      name: "Đồ Chơi Trống Lắc Tay Đại Bằng Nhựa",
      image: "../image/TB42-940-do-choi-trong-lac-tay-dai-size-22cm-cho-be-180x180.jpg",
      price: 49000,
      promotion: "new",
    },
    {
      id: 9,
      name: "Đồ Chơi Thú Nhúng Bơm Hơi",
      image: "../image/TVN01-866-do-choi-thu-nhun-bom-hoi-hinh-con-huou-hang-viet-nam-180x180.jpg",
      price: 154000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Bộ Đồ Chơi Thú Chít Bọ 6 con Túi Lưới",
      image: "../image/037-845-do-choi-thu-chit-bo-12-con-tui-luoi-180x180.jpg",
      price: 24000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Xe Đẩy Tập Đi 3 Con Gà",
      image: "../image/FK001-807-xe-day-tap-di-3-con-ga-bang-go-banh-vien-cao-su-180x180.jpg",
      price: 181000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Đồ Chơi Ném Vòng Vịt Nhí Bằng Nhựa",
      image: "../image/HT710-804-do-choi-nem-vòng-vit-nhi-bang-nhua-tui-luoi-180x180.jpg",
      price: 25000,
      promotion: "new",
    },
    {
      id: 13,
      name: "Đồ Chơi Búa Đập 2 Đầu Nhỏ Bằng Nhựa",
      image: "../image/DP04-8-do-choi-bua-dap-2-dau-nho-bang-nhua-tui-luoi-180x180.jpg",
      price: 15000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Đồ Chơi Trống Lắc Tay Lớn Bằng Nhựa",
      image: "../image/TB44-487-do-choi-trong-lac-tay-lon-bang-nhựa-hinh-hoat-hinh-180x180.jpg",
      price: 18000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Trống Lắc Đàn Cầm Tay BaBy Bằng Nhựa",
      image: "../image/TBD-161-trong-lac-dan-cam-tay-bayby-bang-nhua-180x180.jpg",
      price: 8000,
      promotion: "new",
    },
    {
      id: 16,
      name: "Đồ Chơi Lục Lạc Lắc 3 Banh",
      image: "../image/3BD-316-do-choi-luc-lac-3-banh-o-du-bang-nhua-180x180.jpg",
      price: 10000,
      promotion: "new",
    },
  ],
  doChoiTruyenThong: [
    {
      id: 1,
      name: "Đồ Chơi Đánh Trống",
      image: "../image/1556-do-choi-danh-trong-chap-cheng-4-cai-kem-ghe-ngoi-9008e-5-180x180.jpg",
      price: 210000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Hộp Đồ Chơi 12 Chiếc Nhẫn Bằng Kim Loại",
      image: "../image/1549-hop-do-choi-12-chiec-nhan-bang-kim-loai-cho-be-180x180.jpg",
      price: 24000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Đồ Chơi Kèn Thổi Hình Cây Sáo Bằng Nhựa",
      image: "../image/1547-do-choi-ken-thoi-hinh-cay-sao-phat-ra-am-thanh-180x180.jpg",
      price: 3000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Quạt Vải Xếp Chữ Thư Pháp",
      image: "../image/1540-quat-xep-thu-phap-chu-quat-cam-tay-bang-vai-nan-tre-nhieu-mau-180x180.jpg",
      price: 12000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Bàn Cờ Tướng Lớn Bằng Nhựa",
      image: "../image/1538-ban-co-tuong-lon-bang-nhua-size-44-43-cm-180x180.jpg",
      price: 60000,
      promotion: "new",
    },
    {
      id: 6,
      name: "Đồ Chơi Bấm Nước Máy Game Điện Tử",
      image: "../image/1531-do-choi-bam-nuoc-may-game-dien-tu-2-nut-bam-180x180.jpg",
      price: 12000,
      promotion: "new",
    },
    {
      id: 7,
      name: "Đồ Chơi Con Quay Dựt Day Có Đèn Led",
      image: "../image/1530-do-choi-con-quay-dut-day-co-den-led-983ab-180x180.jpg",
      price: 5000,
      promotion: "new",
    },
    {
      id: 8,
      name: "Đồ Chơi Lính Nhảy Dù",
      image: "../image/1528-do-choi-tui-linh-nhay-du-bang-ni-long-cho-be-180x180.jpg",
      price: 2000,
      promotion: "new",
    },
    {
      id: 9,
      name: "Đồ Chơi Con Quay Spinner",
      image: "../image/1522-do-choi-con-quay-spinner-hand-5-canh-2-tang-hinh-banh-lai-180x180.jpg",
      price: 12000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Lật Đật Mini Size 4cm Bằng Nhựa",
      image: "../image/1507-lat-dat-mini-hinh-hoat-hinh-size-4-cm-cho-be-180x180.jpg",
      price: 3000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Hộp Đồ Chơi Khủng Long",
      image: "../image/1499-do-choi-khung-long-can-tay-dung-pin-co-den-nhac-180x180.jpg",
      price: 120000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Hộp Cờ Cá Ngựa Bằng Nhựa",
      image: "../image/1468-hop-co-ca-ngua-bang-nhua-nhu-yen-co-dua-ngua-horse-race-chess-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 13,
      name: "Trò Chơi Cờ Ô Quan 5 In 1",
      image: "../image/1439-co-o-an-quan-5-in-1-hop-kieng-tro-choi-cho-be-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Trò Chơi Cờ Vua Quốc Tế 3 In 1",
      image: "../image/1433-tro-choi-co-vua-quoc-te-3-in-1-de-nam-cham-bang-nhua-180x180.jpg",
      price: 75000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Hộp Đồ Chơi Câu Cá 2 Cần 15 Cá Dùng Pin",
      image: "../image/1427-hop-do-choi-cau-ca-2-can-15-ca-dung-pin-180x180.jpg",
      price: 45000,
      promotion: "new",
    },
    {
      id: 16,
      name: "Đồ Chơi Chó Cứu Hộ Dùng Pin",
      image: "../image/1426-do-choi-cho-cuu-ho-dung-pin-leo-thang-2-tang-co-den-nhac-180x180.jpg",
      price: 75000,
      promotion: "new",
    },
  ],
  doChoiNhapVai: [
    {
      id: 1,
      name: "Đồ Chơi Gậy Như Ý Tôn Ngộ Không",
      image: "../image/1536-gay-nhu-y-ton-ngo-khong-30-cm-do-choi-tre-em-co-the-keo-dai-thu-gon-180x180.jpg",
      price: 10000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Đồ Chơi Siêu Anh Hùng Bằng Nhựa",
      image: "../image/1490-do-choi-sieu-anh-hung-avengers-bang-nhua-co-den-180x180.jpg",
      price: 35000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Đồ Chơi Khiên Đội Trưởng Mỹ",
      image: "../image/1486-do-choi-khien-doi-truong-my-dung-pin-co-den-nhac-180x180.jpg",
      price: 90000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Phụ Kiện Hóa Trang Kẹp Tóc Elsa",
      image: "../image/1400-phu-kien-hoa-trang-kep-toc-elsa-quyen-truong-vuong-mieng-cho-be-180x180.jpg",
      price: 30000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Băng Đô Cài Tóc Sừng Tuần Lộc Bằng Nhựa",
      image: "../image/1395-bang-do-cai-toc-sung-tuan-loc-bang-nhua-cung-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 6,
      name: "Ba Lô Đồ Chơi Nấu Ăn",
      image: "../image/1382-ba-lo-do-choi-nau-an-bep-lo-bang-nhom-ngoc-bich-10-mon-180x180.jpg",
      price: 100000,
      promotion: "new",
    },
    {
      id: 7,
      name: "Hộp Đồ Chơi Dụng Cụ Sửa Chữa 28 món",
      image: "../image/1358-do-choi-dung-cu-sua-chua-kim-bua-28-mon-bang-nhua-180x180.jpg",
      price: 125000,
      promotion: "new",
    },
    {
      id: 8,
      name: "Đồ Chơi Khay Đựng Dụng Cụ Y Tế",
      image: "../image/1346-do-choi-khay-dung-dung-cu-y-te-bac-si-180x180.jpg",
      price: 50000,
      promotion: "new",
    },
    {
      id: 9,
      name: "Đồ Chơi Dụng Cụ Lau Nhà",
      image: "../image/1324-do-choi-dung-cu-lau-nha-don-dep-nha-cua-9-mon-180x180.jpg",
      price: 35000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Đồ Chơi Giỏ Trái Cây 15 Quả",
      image: "../image/1313-do-choi-gio-trai-cay-15-qua-cac-loai-bang-nhua-180x180.jpg",
      price: 50000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Đồ Chơi Bé Tập Làm Bác Sĩ 26 Món ",
      image: "../image/1309-do-choi-be-tap-lam-bac-si-26-mon-180x180.jpg",
      price: 70000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Đồ Chơi Trang Trí Bàn Tiệc 33 Món",
      image: "../image/1308-do-choi-trang-tri-bang-tiec-cho-be-33-mon-180x180.jpg",
      price: 70000,
      promotion: "new",
    },
    {
      id: 13,
      name: "Đồ Chơi Nhà Bếp Sóng Chén Bằng Nhựa",
      image: "../image/1298-do-choi-nha-bep-nau-bang-nhua-song-chen-180x180.jpg",
      price: 70000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Đồ Chơi Khay Đựng Trái Cây Cắt Bằng Nhựa",
      image: "../image/1297-do-choi-khay-dung-trai-cat-bang-nhua-180x180.jpg",
      price: 50000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Đồ Chơi Thớt Cắt Sushi Bằng Gỗ Hít Nam Châm",
      image: "../image/1255-do-choi-thot-cat-sushi-bang-go-hit-nam-cham-180x180.jpg",
      price: 130000,
      promotion: "new",
    },
    {
      id: 16,
      name: "Đồ Chơi Găng Tay Đấm Bốc USA",
      image: "../image/1246-do-choi-gang-tay-dam-boc-usa-cho-tre-em-180x180.jpg",
      price: 888000,
      promotion: "new",
    },
  ],
  doChoiTriTue: [
    {
      id: 1,
      name: "Đồ Chơi Bảng Viết Tự Xóa",
      image: "../image/1541-do-choi-bang-xoa-bang-viet-tu-xoa-cho-be-bang-nhua-180x180.jpg",
      price: 30000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Bộ Cờ Domino Bằng Nhựa",
      image: "../image/1539-co-domino-cao-thang-bang-nhua-co-hop-nhua-dung-180x180.jpg",
      price: 15000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Bàn Cờ Tướng Lớn Bằng Nhựa",
      image: "../image/1538-ban-co-tuong-lon-bang-nhua-size-44-43-cm-180x180.jpg",
      price: 60000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Đồ Chơi Máy Chơi Game Điện Tử Xếp Hình",
      image: "../image/1506-do-choi-may-choi-game-dien-tu-xep-hinh-xep-gach-dung-pin-180x180.jpg",
      price: 35000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Hộp Cờ Cá Ngựa Bằng Nhựa",
      image: "../image/1468-hop-co-ca-ngua-bang-nhua-nhu-yen-co-dua-ngua-horse-race-chess-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 6,
      name: "Đồ Chơi Rubik Xếp Hình 3 Hàng Bằng Nhựa",
      image: "../image/1447-do-choi-rubik-xep-hinh-3-hang-bang-nhua-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 7,
      name: "Trò Chơi Kêu Lô Tô Bằng Giấy",
      image: "../image/1446-tro-choi-keu-loto-the-gioi-so-bang-giay-va-go-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 8,
      name: "Hột Xí Ngầu Nhiều Màu Trong Suốt",
      image: "../image/1440-hot-xi-ngau-nhieu-mau-xuc-xac-trong-suot-14-mm-bang-nhua-180x180.jpg",
      price: 2000,
      promotion: "new",
    },
    {
      id: 9,
      name: "Cờ Ô Ăn Quan 5 In 1",
      image: "../image/1439-co-o-an-quan-5-in-1-hop-kieng-tro-choi-cho-be-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Bàn Cờ Tỷ Phú Lớn Bằng Nhựa",
      image: "../image/1438-ban-co-ty-phu-lon-lien-hiep-thanh-bang-nhua-size-444-448-mm-180x180.jpg",
      price: 100000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Bàn Cờ Vua Quốc Tế",
      image: "../image/1437-ban-co-quoc-te-co-vua-lien-hiep-thanh-bang-nhua-size-365mm-180x180.jpg",
      price: 90000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Bộ Cờ Thú Và Cờ Đoán 2 In 1",
      image: "../image/1396-co-thu-va-co-doan-2-in-1-lien-hiep-thanh-bang-nhua-melamine-cao-cap-180x180.jpg",
      price: 35000,
      promotion: "new",
    },
    {
      id: 13,
      name: "Hột Đồ Chơi Xúc Xắc Lắc Xí Ngầu Nghệ Hoa Cao Cấp",
      image: "../image/1441-hot-do-choi-xuc-xac-lac-xi-ngau-nghe-hoa-cao-cap-11-12-13-ly-180x180.jpg",
      price: 12000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Bộ 10 Con Dấu Đồ Chơi In Hình Số, Trái Cây",
      image: "../image/1402-bo-10-con-dau-do-choi-in-hinh-mat-cuoi-trai-cay-con-so-cho-be-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Hộp Bút Tô Màu 150 Chi Tiết",
      image: "../image/1384-hop-but-to-mau-150-chi-tiet-dang-cap-sach-cho-be-180x180.jpg",
      price: 70000,
      promotion: "new",
    },
    {
      id: 16,
      name: "Bộ 50 Que Phát Sáng Kèm Nút Gắn Vòng Tay",
      image: "../image/1383-bo-50-que-phat-sang-kem-nut-gan-vong-tay-glow-stick-size-20cm-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
  ],
  doChoiTheThao: [
    {
      id: 1,
      name: "Đồ Chơi Xô Xúc Cát Đi Biển",
      image: "../image/1576-do-choi-xo-xuc-cat-xo-di-bien-bach-tuoc-bang-nhua-180x180.jpg",
      price: 45000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Đồ Chơi Xe Ben Xúc Cát Đi Biển",
      image: "../image/1543-do-choi-xe-ben-xuc-cat-dai-di-bien-size-50-bang-nhua-180x180.jpg",
      price: 180000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Quả Cầu Đá 303",
      image: "../image/1445-cau-da-the-thao-303-180x180.jpg",
      price: 6000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Dây Nhảy Thể Dục WIN",
      image: "../image/1444-day-nhay-the-duc-win-tap-the-duc-cho-tre-em-180x180.jpg",
      price: 25000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Đồ Chơi Ống Hụt Nước 4 Nòng",
      image: "../image/1436-do-choi-ong-thut-nuoc-4-nong-hinh-minion-trong-suot-180x180.jpg",
      price: 65000,
      promotion: "new",
    },
    {
      id: 6,
      name: "Đồ Chơi Banh Tưng Bằng Cao Su",
      image: "../image/1388-do-choi-banh-tung-cung-bang-cao-su-duong-kinh-3-cm-180x180.jpg",
      price: 2000,
      promotion: "new"
    },
    {
      id: 7,
      name: "Đồ Chơi Bắn Bong Bóng Xà Phòng Hình Chú Voi",
      image: "../image/1367-do-choi-ban-bong-bong-xa-phong-hinh-chu-voi-kem-khay-180x180.jpg",
      price: 25000,
      promotion: "new"
    },
    {
      id: 8,
      name: "Đồ Chơi Ống Nhòm Màu Đen Có Dây Đeo",
      image: "../image/1377-do-choi-ong-nhom-mau-den-co-day-deo-180x180.jpg",
      price: 30000,
      promotion: "new"
    },
    {
      id: 9,
      name: "Đồ Chơi Ống Thụt Banh 20 Trái",
      image: "../image/1345-do-choi-ong-thut-banh-20-trai-6-ly-nhua-180x180.jpg",
      price: 300000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Đồ Chơi Đấm Bốc Võ Đài Boxing",
      image: "../image/1338-do-choi-dam-boc-vo-dai-boxing-bao-tay-180x180.jpg",
      price: 100000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Đồ Chơi Súng Bắn Nước Cá Heo",
      image: "../image/1320-do-choi-sung-ban-nuoc-ca-heo-1-binh-du-tru-180x180.jpg",
      price: 15000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Đồ Chơi Còi Thổi Hình Quả Banh",
      image: "../image/1311-do-choi-coi-thoi-hinh-qua-banh-phat-ra-am-thanh-180x180.jpg",
      price: 2000,
      promotion: "new",
    },
    {
      id: 13,
      name: " Đồ Chơi Câu Cá Nam Châm 1 Cần 10 Cá",
      image: "../image/1310-do-choi-cau-ca-nam-cham-1-can-10-ca-kem-be-phao-180x180.jpg",
      price: 50000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Đồ Chơi Bóng Nhựa Nhiều Màu 20 Trái",
      image: "../image/1363-do-choi-bong-nhua-banh-nhua-20-trai-tui-luoi-180x180.jpg",
      price: 25000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Đồ Chơi Phóng Chong Chóng Giật Có Đèn Led",
      image: "../image/1304-do-choi-chong-chong-giat-co-den-led-phat-sang-180x180.jpg",
      price: 20000,
      promotion: "new",
    },
    {
      id: 16,
      name: "Đồ Chơi Ném Vòng Vịt 5 Vòng Đủ Màu",
      image: "../image/1303-do-choi-nem-vong-vit-5-vong-du-mau-duong-kinh-17-cm-180x180.jpg",
      price: 490000,
      promotion: "new",
    },
  ],
};

const productsData2 = {
  newProducts: [
    {
      id: 1,
      name: "Nhiệt Kế Điện Tử",
      image: "../image/10298-nhiet-ke-dien-tu-dan-ngoai-ho-ca-man-hinh-lcd-3d-225x225.jpg",
      price: 75000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Hộp Đồ Chơi Vali Đồ Nghề Sửa Chữa",
      image: "../image/1636-hop-do-choi-va-li-do-nghe-sua-chua-cho-be-215x215.jpg",
      price: 270000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Đồ Chơi Ném Vòng Bằng Nhựa",
      image: "../image/1637-do-choi-nem-vong-bang-nhua-1-vong-1-tru-215x215.jpg",
      price: 20000,
      promotion: "new",
    },
  ],
  popularProduct: [
    {
      id: 1,
      name: "Bộ Bài UNO 108 Lá",
      image: "../image/108UNO-825-bo-bai-uno-108-la-bang-giay-215x215.jpg",
      price: 15000,
    },
    {
      id: 2,
      name: "Bàn Cá Ngựa Lớn",
      image: "../image/ban-ca-ngua-lon-lien-hiep-thanh-215x215.jpg",
      price: 120000,
    },
    {
      id: 3,
      name: "Đồ Chơi Xe Đẩy Siêu Thị Trái Trái Cây",
      image: "../image/1293-do-choi-xe-day-sieu-thi-trai-cay-cho-be-215x215.jpg",
      price: 120000,
      decrease: 100000,
    },
  ],
  discountProduct: [
    {
      id: 1,
      name: "Đồ Chơi Đánh Trống Bằng Nhựa",
      image: "../image/999-249-do-choi-danh-trong-bang-nhua-hoat-hinh-225x225.jpg",
      price: 45000,
      decrease: 35000,
    },
    {
      id: 2,
      name: "Đồ Chơi Súng Bắn Nước",
      image: "../image/1223-do-choi-sung-ban-nuoc-ap-luc-1-binh-size-52-cm-88000-225x225.jpg",
      price: 150000,
      decrease: 120000,
    },
    {
      id: 3,
      name: "Mô Hình Quân Sự Lính Nhựa",
      image: "../image/JL668-968-mo-hinh-quan-su-linh-nhua-militara-action-225x225.jpg",
      price: 83000,
      decrease: 75000,
    },
  ],
};
